### PR TITLE
Latex guide

### PR DESCRIPTION
**Pull request by erooke**
Add a guide for setting up a good local LaTeX environment. I am not sure where this belongs, for the time being I put it under resources. The spacing looks a little silly with it in there⁺ so I'm not sure if that's where it should go.

Things left to do before it is ready for merge:

- [x] Remove the flake commit
- [x] Add VS Code instructions
- [x] Add VS Code plugin instructions
- [x] Test the instructions with a guinea pig or two

⁺The spacing:
image

### CODE REVIEW

**Comment by Joecstarr** [comment]
@erooke is this dead?

**Comment by erooke** [comment]
Ah, I had forgotten about this. It is basically done, I tested it with a guinea pig and they were able to follow the instructions well enough. The only thing missing at this junction is instruction on setting up vs code and how to init a project. I don't personally use vscode so that might take me a second to get throw together.

**Comment by Joecstarr** [comment]
Are you thinking a separate post for vscode? I think that makes sense. It's going to be my "supported" environment for a few things. 

Anything specific to this that needs to be set up? The Latex plugin?

I can do a general "setting up vscode" for the personal site template that you can link to.

**Comment by erooke** [comment]
Sure if you're willing to write instructions on how to configure vscode that would be great. As for what needs to be configured your example config used the following plugins:
- [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop). This does most of the latex stuff
- [LaTeX Utilities](https://marketplace.visualstudio.com/items?itemName=tecosaur.latex-utilities). This adds some more latex stuff
- [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker). This will let you tune the spell checker

I'm not sure how much configuring they need outside of your example config.

**Comment by erooke** [comment]
I changed my mind. I put pretty minimal instructions on how to configure and start a new project. There is a link for them to ask questions by opening an issue as I don't know what people will or won't comprehend.

**Comment by Joecstarr** [comment]
@erooke can you assign me review when you're ready.

**Pull request merged**
